services:
  nginx:
    image: nginx:1.19-alpine
    container_name: container_nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
    
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: container_php
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  
  db:
    image: mysql:8.0
    container_name: container_db
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306